# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-07 23:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('0', '工作报告'), ('1', '项目记录'), ('2', '日程安排')], default='0', max_length=20)),
                ('content', models.TextField(verbose_name='工作日报')),
                ('start_time', models.DateTimeField(default='', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default='', verbose_name='结束时间')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('attention', models.ManyToManyField(blank=True, related_name='attention', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作日报',
                'verbose_name_plural': '工作日报',
            },
        ),
    ]
